# boards/shields/totem-bt/totem.conf
## Common BLE split settings for Totem BT builds on Zephyr 4.1 / ZMK main
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_BLE=y

## Power Management Config
## https://zmk.dev/docs/config/power
CONFIG_ZMK_IDLE_TIMEOUT=10000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=60000

## Disable unused external power control path and allow PM for devices.
CONFIG_ZMK_EXT_POWER=n
CONFIG_PM_DEVICE=y
