## Split keyboards
## https://zmk.dev/docs/config/system#split-keyboards
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

## Keep sleep enabled for normal low-power operation.
## If connectivity issues need to be diagnosed temporarily, this line may be changed to:
## CONFIG_ZMK_SLEEP=n

## Display Configuration
## https://zmk.dev/docs/config/displays
# CONFIG_ZMK_DISPLAY=n

# ## Track words per minute
# CONFIG_ZMK_WPM=y

CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=y

CONFIG_LV_Z_FULL_REFRESH=y
