# .github/workflows/build.yml
name: ZMK Firmware

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */2 *' # run every two months to keep artifacts from expiring

jobs:
  convert-and-store-keymap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Convert keymap
        run: python scripts/convert_keymap.py -c q2c --in-path "$GITHUB_WORKSPACE/config/totem.keymap"

      - name: Upload converted keymaps
        uses: actions/upload-artifact@v4
        with:
          name: keymap_files
          path: ${{ github.workspace }}/config/*.keymap

  build:
    needs: convert-and-store-keymap
    uses: ./.github/workflows/user_config_build.yaml

  keymap_images:
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/draw_keymaps.yaml
    with:
      keymap_patterns: config/*.keymap
      config_path: keymap-drawer/config.yaml
      west_config_path: config
      output_folder: keymap-drawer
      json_path: config
      artifact_name: keymap_layouts
