# .github/workflows/draw_keymaps.yaml
# Reusable workflow for drawing and committing an automated keymap diagram
name: Draw ZMK keymaps

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  workflow_call:
    inputs:
      keymap_patterns:
        description: "Path specification for keymaps to be parsed"
        default: "config/*.keymap"
        required: false
        type: string
      config_path:
        description: "Path to the keymap-drawer configuration file, ignored if non-existent"
        default: "keymap-drawer/config.yaml"
        required: false
        type: string
      west_config_path:
        description: "Path to the folder containing west.yml, e.g. `config`. If specified, west will be initialized to fetch modules defined in west.yml"
        default: ""
        required: false
        type: string
      output_folder:
        description: "Output folder for SVG and YAML files"
        default: "keymap-drawer"
        required: false
        type: string
      json_path:
        description: "Path containing <keymap>.json physical layout description files, ignored if non-existent"
        default: "config"
        required: false
        type: string
      parse_args:
        description: "Map of keyboard names to extra `keymap parse` args, e.g. `corne:'--layer-names Def Lwr Rse Fun'`"
        default: "charybdis: '-b keymap-drawer/charybdis.yaml'"
        required: false
        type: string
      draw_args:
        description: "Map of keyboard names to extra `keymap draw` args, e.g. `corne:'-k corne_rotated -l LAYOUT_split_3x5_3'`"
        default: ""
        required: false
        type: string
      commit_message:
        description: "Commit message for updated images. Ignored if `amend_commit` is `true`."
        default: "keymap-drawer render"
        required: false
        type: string
      amend_commit:
        description: "Whether to amend the last commit instead of creating a new one. Make sure you understand the implications of rewriting the branch history if you use this option!"
        default: true
        required: false
        type: boolean
      install_branch:
        description: "Install keymap-drawer from a git branch, use empty for pypi release (default)"
        default: ""
        required: false
        type: string
      install_repo:
        description: "Install keymap-drawer from a different git remote, primarily for testing changes using a keymap-drawer fork. Ignored if `install_branch` is unset/empty."
        default: "https://github.com/caksoylar/keymap-drawer.git"
        required: false
        type: string
      destination:
        description: "Add the output files to a commit, as artifacts or both, values: `commit`, `artifact`, `both`"
        default: "commit"
        required: false
        type: string
      artifact_name:
        description: "Name of the produced artifact containing SVG and YAML outputs. Ignored if `destination` is `commit`."
        default: "keymap_layouts"
        required: false
        type: string
      fail_on_error:
        description: "Fail the action if an error occurs during parse/draw"
        default: true
        required: false
        type: boolean
    outputs:
      drawings:
        description: "Archive with keymap in YAML and drawing in SVG formats"
        value: ${{ jobs.draw.outputs.drawings }}

jobs:
  draw:
    runs-on: ubuntu-latest
    outputs:
      drawings: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # So the reference to the parent commit is available when amending
          # See:
          # - https://github.com/stefanzweifel/git-auto-commit-action#using---amend-and---no-edit-as-commit-options
          # - https://github.com/stefanzweifel/git-auto-commit-action/issues/159#issuecomment-845347950
          # - https://github.com/actions/checkout
          fetch-depth: ${{ (inputs.amend_commit == true && 2) || 1 }}
          submodules: recursive

      - name: Install keymap-drawer (pypi)
        if: inputs.install_branch == ''
        run: python3 -m pip install keymap-drawer

      - name: Install keymap-drawer (git)
        if: inputs.install_branch != ''
        run: python3 -m pip install "git+${{ inputs.install_repo }}@${{ inputs.install_branch }}"

      - name: Install west
        if: inputs.west_config_path != ''
        run: python3 -m pip install west

      - name: Cache west modules
        if: inputs.west_config_path != ''
        uses: actions/cache@v4
        continue-on-error: true
        env:
          cache_name: cache-zephyr-3.5.0-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache_name }}-${{ hashFiles('**/west.yml', '**/build.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache_name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        if: inputs.west_config_path != ''
        run: |
          ls -Rhl $GITHUB_WORKSPACE
          west init -l ${{ inputs.west_config_path }}

      - name: West Update
        if: inputs.west_config_path != ''
        run: west update

      - name: Parse keymaps
        run: |
          shopt -s globstar nullglob
          [[ -f "${{ inputs.config_path }}" ]] && config_arg=(--config "${{ inputs.config_path }}") || config_arg=()
          for keymap in ${{ inputs.keymap_patterns }}; do
            name="$(basename "${keymap}" .keymap)"
            args="$(echo "${{ inputs.parse_args }}" | yq -r ".\"${name}\" // empty")"
            keymap parse -c "${config_arg[@]}" ${args} "${keymap}" > "${{ inputs.output_folder }}/${name}.yaml"
          done
        shell: bash

      - name: Draw SVGs
        run: |
          shopt -s globstar nullglob
          for yaml in "${{ inputs.output_folder }}"/*.yaml; do
            name="$(basename "${yaml}" .yaml)"
            json=""
            if [[ -f "${{ inputs.json_path }}/${name}.json" ]]; then
              json="-j ${{ inputs.json_path }}/${name}.json"
            fi
            args="$(echo "${{ inputs.draw_args }}" | yq -r ".\"${name}\" // empty")"
            keymap draw ${json} ${args} "${yaml}" > "${{ inputs.output_folder }}/${name}.svg"
          done
        shell: bash

      - name: Archive drawings
        if: inputs.destination != 'commit'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.output_folder }}

      - name: Get last commit message
        if: inputs.destination != 'artifact' && inputs.amend_commit == true
        id: last_commit_message
        run: |
          echo "msg<<EOF" >> "$GITHUB_OUTPUT"
          git log -1 --pretty=%B >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Commit SVGs
        if: inputs.destination != 'artifact'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # The previous commit message is re-used if the previous commit is amended instead of creating a new one when desired
          # See:
          # - https://github.com/stefanzweifel/git-auto-commit-action#using---amend-and---no-edit-as-commit-options
          # - https://github.com/stefanzweifel/git-auto-commit-action/issues/159#issuecomment-845347950
          # - https://github.com/actions/checkout
          commit_message: "${{ (inputs.amend_commit == true && steps.last_commit_message.outputs.msg) || inputs.commit_message }}"
          commit_options: "${{ (inputs.amend_commit == true && '--amend --no-edit') || '' }}"
          push_options: "${{ (inputs.amend_commit == true && '--force-with-lease') || '' }}"
          skip_fetch: ${{ inputs.amend_commit == true }}

      - name: Artifact upload
        id: artifact-upload-step
